services:
    app:
        build: .
        ports:
            - "5000:5000"
        environment:
            - SECRET_KEY=rahasia
            - HOST=db
            - PASSWORD=
            - USER=root
            - DB=mhs_api_pararel
        depends_on:
            - db
        restart: always
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mhs_api_pararel
        ports:
            - "3306:3306"
        restart: always
        
