version: "3"
services:
    app:
        build: .
        ports:
            - "5000:5000"
        environment:
            - SECRET_KEY=rahasia
        depends_on:
            - db
    db:
        image: mysql:5.7
        environment:
            MYSQL_HOST: localhost
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: hishasyl115a1408
            MYSQL_DATABASE: mhs_api_pararel
        ports:
            - "3306:3306"
